/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Algo: () => import('#controllers/AlgoController'),
  Analysis: () => import('#controllers/AnalysisController'),
  Articles: () => import('#controllers/ArticlesController'),
  Dashboard: () => import('#controllers/DashboardController'),
  Logs: () => import('#controllers/LogsController'),
  Metrics: () => import('#controllers/MetricsController'),
  Notifications: () => import('#controllers/NotificationsController'),
  Quant: () => import('#controllers/QuantController'),
  Signals: () => import('#controllers/SignalsController'),
  Tickers: () => import('#controllers/TickersController'),
  Trading: () => import('#controllers/TradingController'),
  Training: () => import('#controllers/TrainingController'),
}
