export enum AppContainerAliasesEnum {
  Logger = "Providers/Logger",
  Finance = "Providers/Finance",
  Mongo = "Providers/MongoDB",
  Jobs = "Providers/Jobs",
  Charts = "Providers/Charts",
  Profiler = "Providers/Profiler",
  Newsletter = "Providers/Newsletter",
  Scraper = "Providers/Scraper",
  ProgressBar = "Providers/ProgressBar",
  Helper = "Providers/Helper",
  StringCleaner = "Providers/StringCleaner",
  Filters = "Providers/Filters",
  Console = "Providers/Console",
}
